// mobile/src/components/auth/TrustDeviceModal.tsx
import React, { useState } from 'react';
import { View, Text, StyleSheet, Modal, TouchableOpacity } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Button } from '../shared';
import { useTheme } from '../../contexts/ThemeContext';
import { useToast } from '../../hooks/useToast';
import { authService } from '../../services/auth/authService';
import { useAuth } from '../../contexts/AuthContext';
import { getDeviceFingerprint } from '../../utils/deviceFingerprint';

interface TrustDeviceModalProps {
  visible: boolean;
  sessionId: string;
  deviceName: string;
  ipAddress: string;
  onClose: () => void;
  onTrusted: () => void;
}

export default function TrustDeviceModal({
  visible,
  sessionId,
  deviceName,
  ipAddress,
  onClose,
  onTrusted,
}: TrustDeviceModalProps) {
  const { isDark } = useTheme();
  const { showSuccess, showError } = useToast();
  const { logout, refreshUser } = useAuth();
  const [isLoading, setIsLoading] = useState(false);

  const handleTrust = async () => {
    if (!sessionId) {
      showError('ID da sessão não encontrado');
      return;
    }

    setIsLoading(true);
    try {
      const response = await authService.trustDevice(sessionId);
      if (response.success) {
        const deviceFingerprint = await getDeviceFingerprint();
        await AsyncStorage.setItem('device_trusted', 'true');
        await AsyncStorage.setItem('device_fingerprint', deviceFingerprint);
        
        showSuccess('Dispositivo confiado com sucesso!');
        await refreshUser();
        onTrusted();
      } else {
        showError(response.message || 'Erro ao confiar dispositivo');
      }
    } catch (error: unknown) {
      const errorMessage = error && typeof error === 'object' && 'response' in error
        ? (error as { response?: { data?: { message?: string } } }).response?.data?.message
        : error instanceof Error
        ? error.message
        : 'Erro ao confiar dispositivo';
      showError(errorMessage || 'Erro ao confiar dispositivo');
    } finally {
      setIsLoading(false);
    }
  };

  const handleClose = async () => {
    if (!isLoading) {
      await logout();
      onClose();
    }
  };

  return (
    <Modal
      visible={visible}
      transparent
      animationType="fade"
      onRequestClose={handleClose}
    >
      <View style={styles.overlay}>
        <View style={[styles.container, { backgroundColor: isDark ? '#1f2937' : '#ffffff' }]}>
          <View style={styles.header}>
            <View style={[styles.iconContainer, { backgroundColor: isDark ? '#374151' : '#fef3c7' }]}>
              <Ionicons name="shield-checkmark" size={32} color={isDark ? '#fbbf24' : '#f59e0b'} />
            </View>
            <Text style={[styles.title, { color: isDark ? '#f9fafb' : '#111827' }]}>
              Confiar neste Dispositivo?
            </Text>
            <Text style={[styles.subtitle, { color: isDark ? '#9ca3af' : '#6b7280' }]}>
              Um novo dispositivo está tentando acessar sua conta. Deseja confiar neste dispositivo?
            </Text>
          </View>

          <View style={[styles.infoContainer, { backgroundColor: isDark ? '#374151' : '#f9fafb' }]}>
            <View style={styles.infoRow}>
              <Ionicons name="phone-portrait-outline" size={16} color={isDark ? '#9ca3af' : '#6b7280'} />
              <Text style={[styles.infoText, { color: isDark ? '#d1d5db' : '#374151' }]}>
                {deviceName}
              </Text>
            </View>
            <View style={styles.infoRow}>
              <Ionicons name="location-outline" size={16} color={isDark ? '#9ca3af' : '#6b7280'} />
              <Text style={[styles.infoText, { color: isDark ? '#d1d5db' : '#374151' }]}>
                {ipAddress}
              </Text>
            </View>
          </View>

          <View style={styles.footer}>
            <Button
              title="Cancelar"
              onPress={handleClose}
              variant="ghost"
              disabled={isLoading}
              style={styles.button}
            />
            <Button
              title="Confiar"
              onPress={handleTrust}
              variant="primary"
              loading={isLoading}
              style={styles.button}
            />
          </View>
        </View>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  container: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  header: {
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  iconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    alignSelf: 'flex-start',
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 8,
    textAlign: 'left',
  },
  subtitle: {
    fontSize: 14,
    textAlign: 'left',
    lineHeight: 20,
  },
  infoContainer: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    gap: 12,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  infoText: {
    fontSize: 14,
    fontWeight: '500',
  },
  footer: {
    flexDirection: 'row',
    gap: 12,
  },
  button: {
    flex: 1,
  },
});

// web/src/components/auth/TrustDeviceModal.vue
<template>
  <BaseModal :show="show" @close="handleClose" size="md" :close-on-overlay="false" :close-on-escape="false">
    <template #header>
      <div class="flex items-center gap-3">
        <div class="p-2 bg-yellow-100 dark:bg-yellow-900/30 rounded-lg">
          <ShieldExclamationIcon class="h-6 w-6 text-yellow-600 dark:text-yellow-400" />
        </div>
        <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100">Dispositivo Não Confiável</h3>
      </div>
    </template>

    <div class="space-y-4">
      <p class="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
        Este dispositivo não está na lista de dispositivos confiáveis. Para sua segurança, você precisa confirmar se deseja confiar neste dispositivo.
      </p>

      <div class="bg-gray-50 dark:bg-gray-700 rounded-lg p-4 space-y-3">
        <div class="flex items-center justify-between">
          <span class="text-sm text-gray-600 dark:text-gray-400">Dispositivo:</span>
          <span class="text-sm font-medium text-gray-900 dark:text-gray-100 text-right">{{ deviceName || 'Desconhecido' }}</span>
        </div>
        <div class="flex items-center justify-between">
          <span class="text-sm text-gray-600 dark:text-gray-400">IP:</span>
          <span class="text-sm font-medium text-gray-900 dark:text-gray-100 text-right">{{ ipAddress || 'Desconhecido' }}</span>
        </div>
      </div>

      <div class="flex items-start gap-3 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
        <InformationCircleIcon class="h-5 w-5 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" />
        <p class="text-xs text-blue-800 dark:text-blue-300 leading-relaxed">
          Ao confiar este dispositivo, você poderá acessar sua conta normalmente. Você pode revogar a confiança a qualquer momento nas configurações.
        </p>
      </div>
    </div>

    <template #footer>
      <div class="flex justify-end space-x-3 w-full">
        <BaseButton variant="ghost" @click="handleClose" :disabled="isLoading">
          Cancelar
        </BaseButton>
        <BaseButton variant="primary" @click="handleTrust" :loading="isLoading">
          Confiar neste Dispositivo
        </BaseButton>
      </div>
    </template>
  </BaseModal>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { ShieldExclamationIcon, InformationCircleIcon } from '@heroicons/vue/24/outline'
import { BaseModal, BaseButton } from '@/components/ui'
import { useToast } from '@/hooks/useToast'
import authApi from '@/api/auth'
import { getDeviceFingerprint } from '@/utils/deviceFingerprint'

interface Props {
  show: boolean
  sessionId: string
  deviceName?: string
  ipAddress?: string
}

interface Emits {
  (e: 'close'): void
  (e: 'trusted'): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()
const toast = useToast()

const isLoading = ref(false)

const handleTrust = async () => {
  isLoading.value = true
  try {
    const response = await authApi.trustDevice(props.sessionId)
    if (response.success) {
      localStorage.setItem('device_trusted', 'true')
      const deviceFingerprint = await getDeviceFingerprint()
      localStorage.setItem('device_fingerprint', deviceFingerprint)
      
      toast.success('Dispositivo confiado com sucesso!')
      emit('trusted')
    } else {
      toast.error(response.message || 'Erro ao confiar dispositivo')
    }
  } catch (error: unknown) {
    const errorMessage = error && typeof error === 'object' && 'response' in error
      ? (error as { response?: { data?: { message?: string } } }).response?.data?.message
      : error instanceof Error ? error.message : 'Erro ao confiar dispositivo';
    toast.error(errorMessage)
  } finally {
    isLoading.value = false
  }
}

const handleClose = () => {
  if (!isLoading.value) {
    emit('close')
  }
}
</script>
