// web/src/components/ui/TotpCode.vue
<template>
  <div class="totp-container">
    <div class="totp-code-wrapper">
      <div class="totp-code" :class="{ 'animate-pulse': currentTimeRemaining < 5 }">
        {{ formattedCode }}
      </div>
      
      <div class="totp-timer-container">
        <div class="totp-timer" :style="timerStyle">
          <div class="totp-timer-inner">
            {{ currentTimeRemaining }}s
          </div>
        </div>
      </div>
    </div>
    
    <div class="totp-actions">
      <BaseButton
        variant="ghost"
        size="sm"
        @click="copyCode"
        :disabled="!currentCode"
      >
        <ClipboardIcon class="w-4 h-4 mr-1" />
        Copiar
      </BaseButton>
      
      <BaseButton
        variant="ghost"
        size="sm"
        @click="refreshCode"
        :loading="isRefreshing"
      >
        <ArrowPathIcon class="w-4 h-4 mr-1" />
        Atualizar
      </BaseButton>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted, watch } from 'vue'
import { useToast } from '@/hooks/useToast'
import { ClipboardIcon, ArrowPathIcon } from '@heroicons/vue/24/outline'
import BaseButton from './BaseButton.vue'
import { TOTPClient, type TOTPCode } from '@/utils/totpClient'
import { copyToClipboard } from '@/utils/clipboard'

interface Props {
  secret?: string | null 
  code?: string | null 
  timeRemaining?: number | null 
  period?: number | null 
  autoRefresh?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  autoRefresh: true
})

const emit = defineEmits<{
  refresh: []
}>()

const toast = useToast()
const isRefreshing = ref(false)
let intervalId: number | null = null


const currentCode = ref<string>('')
const currentTimeRemaining = ref<number>(30)
const currentPeriod = ref<number>(30)


const generateTotpCode = () => {
  if (!props.secret) {
    return
  }
  
  try {
    const totpData = TOTPClient.generateCurrentCode(props.secret)
    currentCode.value = totpData.code
    currentTimeRemaining.value = totpData.timeRemaining
    currentPeriod.value = totpData.period
  } catch (error) {
    currentCode.value = '------'
  }
}


const displayCode = computed(() => {
  return currentCode.value || props.code || '------'
})

const displayTimeRemaining = computed(() => {
  return currentTimeRemaining.value || props.timeRemaining || 30
})

const displayPeriod = computed(() => {
  return currentPeriod.value || props.period || 30
})

const formattedCode = computed(() => {
  if (!displayCode.value || displayCode.value === '------') return '------'
  return displayCode.value.replace(/(.{3})/g, '$1 ').trim()
})

const timerStyle = computed(() => {
  const progress = (displayTimeRemaining.value / displayPeriod.value) * 100
  return {
    '--progress': `${progress * 3.6}deg`
  }
})

const copyCode = async () => {
  if (!displayCode.value || displayCode.value === '------') return

  const cleanCode = displayCode.value.replace(/\D/g, '').slice(0, 6)
  if (cleanCode.length !== 6) {
    toast.error('Código indisponível')
    return
  }
  
  const result = await copyToClipboard(cleanCode)
  if (result.success) {
    toast.success('Código copiado!')
  } else {
    toast.error(result.message)
  }
}

const refreshCode = async () => {
  isRefreshing.value = true
  
  
  if (props.secret) {
    generateTotpCode()
  } else {
    
    emit('refresh')
  }
  
  setTimeout(() => {
    isRefreshing.value = false
  }, 1000)
}

const startTimer = () => {
  if (intervalId) return
  
  intervalId = window.setInterval(() => {
    if (props.secret) {
      
      generateTotpCode()
    } else {
      
      if (displayTimeRemaining.value <= 1) {
        emit('refresh')
      }
    }
  }, 1000)
}

const stopTimer = () => {
  if (intervalId) {
    clearInterval(intervalId)
    intervalId = null
  }
}


watch(() => props.secret, (newSecret) => {
  if (newSecret) {
    generateTotpCode()
  }
}, { immediate: true })

onMounted(() => {
  if (props.secret) {
    generateTotpCode()
  }
  
  if (props.autoRefresh) {
    startTimer()
  }
})

onUnmounted(() => {
  stopTimer()
})
</script>

<style scoped>
.totp-container {
  @apply bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-4 space-y-4;
}

.totp-code-wrapper {
  @apply relative;
}

.totp-code {
  @apply font-mono text-3xl font-bold text-center text-gray-900 dark:text-gray-100 bg-gray-50 dark:bg-gray-900 rounded-lg py-4 px-6 border-2 border-dashed border-gray-300 dark:border-gray-600 tracking-widest;
}

.totp-timer-container {
  @apply absolute -top-2 -right-2;
}

.totp-timer {
  @apply w-8 h-8 rounded-full bg-white dark:bg-gray-800 border-2 border-gray-200 dark:border-gray-600 flex items-center justify-center;
  background: conic-gradient(from 0deg, #3b82f6 0deg, #3b82f6 var(--progress), #e5e7eb var(--progress), #e5e7eb 360deg);
}

.totp-timer-inner {
  @apply w-6 h-6 bg-white dark:bg-gray-800 rounded-full flex items-center justify-center text-xs font-medium text-gray-700 dark:text-gray-200;
}

.totp-actions {
  @apply flex justify-center space-x-2;
}
</style>

// mobile/src/components/totp/TotpCode.tsx
import React, { useEffect, useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../contexts/ThemeContext';
import { Button } from '../shared/Button';
import * as Clipboard from 'expo-clipboard';
import { TOTPClient, type TOTPCode } from '../../utils/totpClient';

interface TotpCodeProps {
  secret?: string; 
  code?: string; 
  timeRemaining?: number; 
  period?: number; 
  onRefresh?: () => void;
  onCopy?: () => void;
}

export const TotpCode: React.FC<TotpCodeProps> = ({
  secret,
  code,
  timeRemaining = 0,
  period = 30,
  onRefresh,
  onCopy,
}) => {
  const { isDark } = useTheme();
  const [currentCode, setCurrentCode] = useState<string>('');
  const [currentTimeRemaining, setCurrentTimeRemaining] = useState<number>(30);
  const [currentPeriod, setCurrentPeriod] = useState<number>(30);

  
  const generateTotpCode = () => {
    if (!secret) return;
    
    try {
      const totpData = TOTPClient.generateCurrentCode(secret);
      setCurrentCode(totpData.code);
      setCurrentTimeRemaining(totpData.timeRemaining);
      setCurrentPeriod(totpData.period);
    } catch (error) {
      console.error('Erro ao gerar código TOTP:', error);
      setCurrentCode('------');
    }
  };

  
  const displayCode = currentCode || code || '------';
  const displayTimeRemaining = currentTimeRemaining || timeRemaining || 30;
  const displayPeriod = currentPeriod || period || 30;

  useEffect(() => {
    if (secret) {
      generateTotpCode();
    } else {
      setCurrentTimeRemaining(timeRemaining);
    }
  }, [secret, timeRemaining]);

  useEffect(() => {
    if (secret) {
      
      const timer = setInterval(() => {
        generateTotpCode();
      }, 1000);

      return () => clearInterval(timer);
    } else {
      
      if (displayTimeRemaining <= 0) return;

      const timer = setInterval(() => {
        setCurrentTimeRemaining(prev => {
          if (prev <= 1) {
            onRefresh?.();
            return displayPeriod;
          }
          return prev - 1;
        });
      }, 1000);

      return () => clearInterval(timer);
    }
  }, [secret, displayTimeRemaining, displayPeriod, onRefresh]);

  const formattedCode = displayCode ? displayCode.replace(/(.{3})/g, '$1 ').trim() : '------';
  const progress = (displayTimeRemaining / displayPeriod) * 100;

  const handleCopy = async () => {
    if (displayCode && displayCode !== '------') {
      const cleanCode = displayCode.replace(/\D/g, '').slice(0, 6);

      if (cleanCode.length !== 6) {
        console.error('Código TOTP indisponível para cópia');
        return;
      }

      try {
        await Clipboard.setStringAsync(cleanCode);
        onCopy?.();
      } catch (error) {
        console.error('Erro ao copiar código:', error);
      }
    }
  };

  const handleRefresh = () => {
    if (secret) {
      
      generateTotpCode();
    } else {
      
      onRefresh?.();
    }
  };

  const styles = StyleSheet.create({
    container: {
      backgroundColor: isDark ? '#1f2937' : '#ffffff',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: isDark ? '#374151' : '#e5e7eb',
      padding: 24,
      gap: 16,
    },
    codeWrapper: {
      position: 'relative',
      alignItems: 'center',
    },
    code: {
      fontFamily: 'monospace',
      fontSize: 32,
      fontWeight: 'bold',
      textAlign: 'center',
      backgroundColor: isDark ? '#374151' : '#f9fafb',
      borderRadius: 12,
      paddingVertical: 16,
      paddingHorizontal: 24,
      borderWidth: 2,
      borderStyle: 'dashed',
      borderColor: isDark ? '#4b5563' : '#d1d5db',
      letterSpacing: 4,
      color: isDark ? '#f9fafb' : '#111827',
      opacity: currentTimeRemaining < 5 ? 0.7 : 1,
    },
    timerContainer: {
      position: 'absolute',
      top: -8,
      right: -8,
    },
    timer: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: isDark ? '#1f2937' : '#ffffff',
      borderWidth: 2,
      borderColor: isDark ? '#4b5563' : '#d1d5db',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    timerInner: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: isDark ? '#1f2937' : '#ffffff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    timerText: {
      fontSize: 10,
      fontWeight: '600',
      color: isDark ? '#f9fafb' : '#111827',
    },
    progressRing: {
      position: 'absolute',
      width: 32,
      height: 32,
      borderRadius: 16,
    },
    actions: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 8,
    },
    actionButton: {
      flex: 1,
    },
  });

  return (
    <View style={styles.container}>
      <View style={styles.codeWrapper}>
        <Text style={styles.code}>{formattedCode}</Text>
        
        <View style={styles.timerContainer}>
          <View style={styles.timer}>
            <View style={styles.timerInner}>
              <Text style={styles.timerText}>{displayTimeRemaining}s</Text>
            </View>
            {}
          </View>
        </View>
      </View>
      
      <View style={styles.actions}>
        <Button
          title="Copiar"
          onPress={handleCopy}
          variant="secondary"
          size="sm"
          style={styles.actionButton}
          disabled={!displayCode || displayCode === '------'}
        />
        <Button
          title="Atualizar"
          onPress={handleRefresh}
          variant="secondary"
          size="sm"
          style={styles.actionButton}
        />
      </View>
    </View>
  );
};
