// web/src/components/ui/PasswordGeneratorModal.vue
<template>
  <BaseModal :show="show" @close="$emit('close')" size="lg">
    <template #header>
      <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100">Gerador de Senha</h3>
    </template>

    <div class="space-y-6">
      <div class="space-y-4">
        <h4 class="text-md font-medium text-gray-900 dark:text-gray-100">Opções de Geração</h4>

        <div class="flex items-center justify-between">
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
            Comprimento
          </label>
          <BaseInput
            v-model="length"
            type="number"
            :min="1"
            :max="128"
            class="w-20"
          />
        </div>

        <div class="flex items-center justify-between">
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
            Maiúsculas (A-Z)
          </label>
          <label class="relative inline-flex items-center cursor-pointer">
            <input
              type="checkbox"
              v-model="includeUppercase"
              class="sr-only peer"
            />
            <div class="w-11 h-6 bg-gray-200 dark:bg-gray-700 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary-600"></div>
          </label>
        </div>

        <div class="flex items-center justify-between">
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
            Minúsculas (a-z)
          </label>
          <label class="relative inline-flex items-center cursor-pointer">
            <input
              type="checkbox"
              v-model="includeLowercase"
              class="sr-only peer"
            />
            <div class="w-11 h-6 bg-gray-200 dark:bg-gray-700 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary-600"></div>
          </label>
        </div>

        <div class="flex items-center justify-between">
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
            Números (0-9)
          </label>
          <label class="relative inline-flex items-center cursor-pointer">
            <input
              type="checkbox"
              v-model="includeNumbers"
              class="sr-only peer"
            />
            <div class="w-11 h-6 bg-gray-200 dark:bg-gray-700 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary-600"></div>
          </label>
        </div>

        <div class="flex items-center justify-between">
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
            Símbolos (!@#$...)
          </label>
          <label class="relative inline-flex items-center cursor-pointer">
            <input
              type="checkbox"
              v-model="includeSymbols"
              class="sr-only peer"
            />
            <div class="w-11 h-6 bg-gray-200 dark:bg-gray-700 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary-600"></div>
          </label>
        </div>
      </div>

      <div class="space-y-2">
        <h4 class="text-md font-medium text-gray-900 dark:text-gray-100">Senha Gerada</h4>
        
        <BaseInput
          v-model="password"
          :type="showPassword ? 'text' : 'password'"
          placeholder="Senha será gerada aqui..."
        >
          <template #right-icon>
            <button
              type="button"
              @click="showPassword = !showPassword"
              class="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
            >
              <EyeIcon v-if="showPassword" class="h-5 w-5" />
              <EyeSlashIcon v-else class="h-5 w-5" />
            </button>
          </template>
        </BaseInput>
      </div>
    </div>

    <template #footer>
      <div class="flex justify-end space-x-3">
        <BaseButton
          variant="primary"
          @click="generatePassword"
          :loading="isGenerating"
        >
          Gerar
        </BaseButton>
        <BaseButton
          variant="secondary"
          @click="handleUsePassword"
          :disabled="!password"
        >
          Usar
        </BaseButton>
      </div>
    </template>
  </BaseModal>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { EyeIcon, EyeSlashIcon } from '@heroicons/vue/24/outline'
import { BaseModal, BaseInput, BaseButton } from '@/components/ui'
import { useToast } from '@/hooks/useToast'

interface Props {
  show: boolean
  initialPassword?: string
}

interface Emits {
  (e: 'close'): void
  (e: 'password-generated', password: string): void
}

const props = withDefaults(defineProps<Props>(), {
  initialPassword: ''
})

const emit = defineEmits<Emits>()
const toast = useToast()

const password = ref(props.initialPassword)
const showPassword = ref(false)
const length = ref('16')
const includeUppercase = ref(true)
const includeLowercase = ref(true)
const includeNumbers = ref(true)
const includeSymbols = ref(true)
const isGenerating = ref(false)

watch(() => props.initialPassword, (newPassword) => {
  if (newPassword && props.show) {
    password.value = newPassword
  }
})

watch(() => props.show, (show) => {
  if (show && props.initialPassword) {
    password.value = props.initialPassword
  }
})

const generatePassword = () => {
  isGenerating.value = true
  
  const lengthNum = parseInt(length.value, 10)
  if (isNaN(lengthNum) || lengthNum < 1 || lengthNum > 128) {
    toast.error('Comprimento deve ser entre 1 e 128')
    isGenerating.value = false
    return
  }
  
  let charset = ''
  if (includeLowercase.value) charset += 'abcdefghijklmnopqrstuvwxyz'
  if (includeUppercase.value) charset += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  if (includeNumbers.value) charset += '0123456789'
  if (includeSymbols.value) charset += '!@#$%^&*'
  
  if (charset.length === 0) {
    toast.error('Selecione pelo menos um tipo de caractere')
    isGenerating.value = false
    return
  }
  
  let newPassword = ''
  for (let i = 0; i < lengthNum; i++) {
    newPassword += charset.charAt(Math.floor(Math.random() * charset.length))
  }
  
  password.value = newPassword
  showPassword.value = true
  isGenerating.value = false
}

const handleUsePassword = () => {
  if (password.value) {
    emit('password-generated', password.value)
    emit('close')
    toast.success('Senha aplicada!')
  }
}
</script>

// mobile/src/components/shared/PasswordGeneratorModal.tsx
import React, { useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView, Switch } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Modal } from './Modal';
import { Input } from './Input';
import { Button } from './Button';
import { useTheme } from '../../contexts/ThemeContext';
import { useToast } from '../../hooks/useToast';
import { SafeAreaView } from 'react-native-safe-area-context';

interface PasswordGeneratorModalProps {
  visible: boolean;
  onClose: () => void;
  onPasswordGenerated: (password: string) => void;
  initialPassword?: string;
}

export const PasswordGeneratorModal: React.FC<PasswordGeneratorModalProps> = ({
  visible,
  onClose,
  onPasswordGenerated,
  initialPassword = '',
}) => {
  const { isDark } = useTheme();
  const { showSuccess } = useToast();
  const [password, setPassword] = useState(initialPassword);
  const [showPassword, setShowPassword] = useState(false);
  const [length, setLength] = useState('16');
  const [includeUppercase, setIncludeUppercase] = useState(true);
  const [includeLowercase, setIncludeLowercase] = useState(true);
  const [includeNumbers, setIncludeNumbers] = useState(true);
  const [includeSymbols, setIncludeSymbols] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);

  
  React.useEffect(() => {
    if (initialPassword && visible) {
      setPassword(initialPassword);
    }
  }, [initialPassword, visible]);

  const generatePassword = () => {
    setIsGenerating(true);
    
    const lengthNum = parseInt(length, 10);
    if (isNaN(lengthNum) || lengthNum < 1 || lengthNum > 128) {
      showSuccess('Comprimento deve ser entre 1 e 128');
      setIsGenerating(false);
      return;
    }
    
    
    let charset = '';
    if (includeLowercase) charset += 'abcdefghijklmnopqrstuvwxyz';
    if (includeUppercase) charset += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    if (includeNumbers) charset += '0123456789';
    if (includeSymbols) charset += '!@#$%^&*';
    
    if (charset.length === 0) {
      showSuccess('Selecione pelo menos um tipo de caractere');
      setIsGenerating(false);
      return;
    }
    
    
    let newPassword = '';
    for (let i = 0; i < lengthNum; i++) {
      newPassword += charset.charAt(Math.floor(Math.random() * charset.length));
    }
    
    setPassword(newPassword);
    setShowPassword(true);
    setIsGenerating(false);
  };

  const handleUsePassword = () => {
    if (password) {
      onPasswordGenerated(password);
      onClose();
      showSuccess('Senha aplicada!');
    }
  };


  const styles = StyleSheet.create({
    container: {
      gap: 16,
      flex: 1,
    },
    passwordSection: {
      gap: 12,
    },
    passwordDisplay: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    passwordInput: {
      flex: 1,
    },
    optionsSection: {
      gap: 12,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: isDark ? '#f9fafb' : '#111827',
    },
    optionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    optionLabel: {
      fontSize: 14,
      color: isDark ? '#f9fafb' : '#111827',
      flex: 1,
    },
    lengthInput: {
      width: 80,
    },
    actions: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 8,
    },
    actionButton: {
      flex: 1,
    },
  });

  return (
    <Modal
      visible={visible}
      onClose={onClose}
      title="Gerador de Senha"
      size="lg"
    >
      <ScrollView 
        style={styles.container} 
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{ 
          flexGrow: 1,
          paddingBottom: 20
        }}
        keyboardShouldPersistTaps="handled"
        bounces={false}
      >
        <View style={styles.optionsSection}>
          <Text style={styles.sectionTitle}>Opções de Geração</Text>

          <View style={styles.optionRow}>
            <Text style={styles.optionLabel}>Comprimento</Text>
            <Input
              value={length}
              onChangeText={setLength}
              keyboardType="numeric"
              style={styles.lengthInput}
            />
          </View>

          <View style={styles.optionRow}>
            <Text style={styles.optionLabel}>Maiúsculas (A-Z)</Text>
            <Switch
              value={includeUppercase}
              onValueChange={setIncludeUppercase}
              trackColor={{ false: isDark ? '#374151' : '#e5e7eb', true: '#16a34a' }}
              thumbColor={includeUppercase ? '#ffffff' : '#f4f3f4'}
            />
          </View>

          <View style={styles.optionRow}>
            <Text style={styles.optionLabel}>Minúsculas (a-z)</Text>
            <Switch
              value={includeLowercase}
              onValueChange={setIncludeLowercase}
              trackColor={{ false: isDark ? '#374151' : '#e5e7eb', true: '#16a34a' }}
              thumbColor={includeLowercase ? '#ffffff' : '#f4f3f4'}
            />
          </View>

          <View style={styles.optionRow}>
            <Text style={styles.optionLabel}>Números (0-9)</Text>
            <Switch
              value={includeNumbers}
              onValueChange={setIncludeNumbers}
              trackColor={{ false: isDark ? '#374151' : '#e5e7eb', true: '#16a34a' }}
              thumbColor={includeNumbers ? '#ffffff' : '#f4f3f4'}
            />
          </View>

          <View style={styles.optionRow}>
            <Text style={styles.optionLabel}>Símbolos (!@#$...)</Text>
            <Switch
              value={includeSymbols}
              onValueChange={setIncludeSymbols}
              trackColor={{ false: isDark ? '#374151' : '#e5e7eb', true: '#16a34a' }}
              thumbColor={includeSymbols ? '#ffffff' : '#f4f3f4'}
            />
          </View>
        </View>

        <View style={styles.passwordSection}>
          <Text style={styles.sectionTitle}>Senha Gerada</Text>
          
          <View style={styles.passwordDisplay}>
            <Input
              value={password}
              onChangeText={setPassword}
              placeholder="Senha será gerada aqui..."
              secureTextEntry={!showPassword}
              style={styles.passwordInput}
              rightIcon={
                <TouchableOpacity onPress={() => setShowPassword(!showPassword)}>
                  <Ionicons
                    name={showPassword ? "eye-off-outline" : "eye-outline"}
                    size={20}
                    color={isDark ? '#9ca3af' : '#6b7280'}
                  />
                </TouchableOpacity>
              }
            />
          </View>
        </View>

        <View style={styles.actions}>
          <Button
            title="Gerar"
            onPress={generatePassword}
            loading={isGenerating}
            variant="primary"
            style={styles.actionButton}
          />
          <Button
            title="Usar"
            onPress={handleUsePassword}
            disabled={!password}
            variant="secondary"
            style={styles.actionButton}
          />
        </View>
      </ScrollView>
    </Modal>
  );
};
