// web/src/components/ui/SearchInput.vue
<template>
  <div class="search-input-container">
    <div class="search-input-wrapper">
      <MagnifyingGlassIcon class="search-icon" />
      <input
        ref="inputRef"
        v-model="inputValue"
        type="text"
        :placeholder="placeholder"
        :disabled="disabled"
        class="search-input"
        @input="handleInput"
        @focus="handleFocus"
        @blur="handleBlur"
        @keydown.enter="handleEnter"
        @keydown.escape="handleEscape"
      />
      <button
        v-if="showClearButton && inputValue"
        type="button"
        class="clear-button"
        @click="handleClear"
        :disabled="disabled"
      >
        <XMarkIcon class="clear-icon" />
      </button>
    </div>
    
    <!-- Loading indicator -->
    <div v-if="isSearching" class="search-loading">
      <div class="loading-spinner"></div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from 'vue'
import { MagnifyingGlassIcon, XMarkIcon } from '@heroicons/vue/24/outline'

interface Props {
  modelValue?: string
  placeholder?: string
  debounceMs?: number
  disabled?: boolean
  autoFocus?: boolean
  showClearButton?: boolean
  minLength?: number
}

interface Emits {
  (e: 'update:modelValue', value: string): void
  (e: 'search', value: string): void
  (e: 'clear'): void
  (e: 'focus'): void
  (e: 'blur'): void
  (e: 'enter', value: string): void
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: 'Pesquisar...',
  debounceMs: 300,
  disabled: false,
  autoFocus: false,
  showClearButton: true,
  minLength: 1
})

const emit = defineEmits<Emits>()

const inputRef = ref<HTMLInputElement>()
const inputValue = ref<string>(props.modelValue || '')
const isSearching = ref<boolean>(false)
let debounceTimer: number | null = null
let searchTimeout: number | null = null

// Debounce function
const debounce = (func: Function, delay: number) => {
  return (...args: any[]) => {
    if (debounceTimer) {
      clearTimeout(debounceTimer)
    }
    debounceTimer = window.setTimeout(() => func.apply(this, args), delay)
  }
}

// Debounced search function
const debouncedSearch = debounce((value: string) => {
  if (value.length >= props.minLength) {
    isSearching.value = true
    emit('search', value)
    
    // Simulate search completion (you can remove this if you handle it differently)
    searchTimeout = window.setTimeout(() => {
      isSearching.value = false
    }, 200)
  } else if (value.length === 0) {
    // Clear search immediately when input is empty
    isSearching.value = false
    emit('search', '')
  }
}, props.debounceMs)

// Handle input changes
const handleInput = () => {
  emit('update:modelValue', inputValue.value)
  debouncedSearch(inputValue.value)
}

// Handle clear button
const handleClear = () => {
  inputValue.value = ''
  emit('update:modelValue', '')
  emit('clear')
  emit('search', '')
  isSearching.value = false
  
  // Clear any pending debounced calls
  if (debounceTimer) {
    clearTimeout(debounceTimer)
    debounceTimer = null
  }
  
  // Focus back to input
  inputRef.value?.focus()
}

// Handle enter key
const handleEnter = () => {
  if (debounceTimer) {
    clearTimeout(debounceTimer)
    debounceTimer = null
  }
  emit('enter', inputValue.value)
  emit('search', inputValue.value)
}

// Handle escape key
const handleEscape = () => {
  handleClear()
}

// Handle focus
const handleFocus = () => {
  emit('focus')
}

// Handle blur
const handleBlur = () => {
  emit('blur')
}

// Watch for external modelValue changes
watch(() => props.modelValue, (newValue) => {
  if (newValue !== inputValue.value) {
    inputValue.value = newValue || ''
  }
})

// Auto focus on mount
onMounted(() => {
  if (props.autoFocus) {
    inputRef.value?.focus()
  }
})

// Cleanup timers on unmount
onUnmounted(() => {
  if (debounceTimer) {
    clearTimeout(debounceTimer)
  }
  if (searchTimeout) {
    clearTimeout(searchTimeout)
  }
})

// Expose methods for parent component
defineExpose({
  focus: () => inputRef.value?.focus(),
  blur: () => inputRef.value?.blur(),
  clear: handleClear,
  getValue: () => inputValue.value
})
</script>

<style scoped>
.search-input-container {
  @apply relative w-full;
}

.search-input-wrapper {
  @apply relative flex items-center;
}

.search-input {
  @apply w-full pl-10 pr-10 py-2 border border-gray-300 rounded-lg 
         focus:ring-2 focus:ring-blue-500 focus:border-blue-500 
         disabled:bg-gray-100 disabled:cursor-not-allowed
         placeholder-gray-500 text-gray-900;
}

.search-icon {
  @apply absolute left-3 h-5 w-5 text-gray-400 pointer-events-none;
}

.clear-button {
  @apply absolute right-3 p-1 rounded-full hover:bg-gray-100 
         focus:outline-none focus:ring-2 focus:ring-blue-500 
         disabled:opacity-50 disabled:cursor-not-allowed;
}

.clear-icon {
  @apply h-4 w-4 text-gray-400;
}

.search-loading {
  @apply absolute right-12 top-1/2 transform -translate-y-1/2;
}

.loading-spinner {
  @apply h-4 w-4 border-2 border-gray-300 border-t-blue-500 rounded-full animate-spin;
}

/* Dark mode support */
@media (prefers-color-scheme: dark) {
  .search-input {
    @apply bg-gray-800 border-gray-600 text-white placeholder-gray-400
           focus:ring-blue-400 focus:border-blue-400;
  }
  
  .search-icon {
    @apply text-gray-500;
  }
  
  .clear-button {
    @apply hover:bg-gray-700;
  }
  
  .clear-icon {
    @apply text-gray-500;
  }
  
  .loading-spinner {
    @apply border-gray-600 border-t-blue-400;
  }
}
</style>

// mobile/src/components/shared/SearchInput.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { View, TextInput, TouchableOpacity, StyleSheet, ActivityIndicator } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../contexts/ThemeContext';

interface SearchInputProps {
  value?: string;
  placeholder?: string;
  debounceMs?: number;
  disabled?: boolean;
  autoFocus?: boolean;
  showClearButton?: boolean;
  minLength?: number;
  onChangeText?: (text: string) => void;
  onSearch?: (text: string) => void;
  onClear?: () => void;
  onFocus?: () => void;
  onBlur?: () => void;
  onEnter?: (text: string) => void;
}

export const SearchInput: React.FC<SearchInputProps> = ({
  value = '',
  placeholder = 'Pesquisar...',
  debounceMs = 300,
  disabled = false,
  autoFocus = false,
  showClearButton = true,
  minLength = 1,
  onChangeText,
  onSearch,
  onClear,
  onFocus,
  onBlur,
  onEnter,
}) => {
  const { isDark } = useTheme();
  const [inputValue, setInputValue] = useState<string>(value);
  const [isSearching, setIsSearching] = useState<boolean>(false);
  const inputRef = useRef<TextInput>(null);
  const debounceTimer = useRef<NodeJS.Timeout | null>(null);
  const searchTimeout = useRef<NodeJS.Timeout | null>(null);

  // Debounce function
  const debounce = useCallback((func: Function, delay: number) => {
    return (...args: any[]) => {
      if (debounceTimer.current) {
        clearTimeout(debounceTimer.current);
      }
      debounceTimer.current = setTimeout(() => func.apply(null, args), delay);
    };
  }, []);

  // Debounced search function
  const debouncedSearch = useCallback(
    debounce((searchValue: string) => {
      if (searchValue.length >= minLength) {
        setIsSearching(true);
        onSearch?.(searchValue);
        
        // Simulate search completion
        searchTimeout.current = setTimeout(() => {
          setIsSearching(false);
        }, 200);
      } else if (searchValue.length === 0) {
        // Clear search immediately when input is empty
        setIsSearching(false);
        onSearch?.('');
      }
    }, debounceMs),
    [debounceMs, minLength, onSearch]
  );

  // Handle input changes
  const handleInputChange = useCallback((text: string) => {
    setInputValue(text);
    onChangeText?.(text);
    debouncedSearch(text);
  }, [onChangeText, debouncedSearch]);

  // Handle clear button
  const handleClear = useCallback(() => {
    setInputValue('');
    onChangeText?.('');
    onClear?.();
    onSearch?.('');
    setIsSearching(false);
    
    // Clear any pending debounced calls
    if (debounceTimer.current) {
      clearTimeout(debounceTimer.current);
      debounceTimer.current = null;
    }
    
    // Focus back to input
    inputRef.current?.focus();
  }, [onChangeText, onClear, onSearch]);

  // Handle submit (enter key equivalent)
  const handleSubmit = useCallback(() => {
    if (debounceTimer.current) {
      clearTimeout(debounceTimer.current);
      debounceTimer.current = null;
    }
    onEnter?.(inputValue);
    onSearch?.(inputValue);
  }, [inputValue, onEnter, onSearch]);

  // Handle focus
  const handleFocus = useCallback(() => {
    onFocus?.();
  }, [onFocus]);

  // Handle blur
  const handleBlur = useCallback(() => {
    onBlur?.();
  }, [onBlur]);

  // Update internal value when prop changes
  useEffect(() => {
    if (value !== inputValue) {
      setInputValue(value);
    }
  }, [value]);

  // Auto focus on mount
  useEffect(() => {
    if (autoFocus) {
      inputRef.current?.focus();
    }
  }, [autoFocus]);

  // Cleanup timers on unmount
  useEffect(() => {
    return () => {
      if (debounceTimer.current) {
        clearTimeout(debounceTimer.current);
      }
      if (searchTimeout.current) {
        clearTimeout(searchTimeout.current);
      }
    };
  }, []);

  const styles = StyleSheet.create({
    container: {
      width: '100%',
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      position: 'relative',
    },
    input: {
      flex: 1,
      paddingLeft: 40,
      paddingRight: showClearButton ? 40 : 12,
      paddingVertical: 12,
      fontSize: 16,
      borderRadius: 8,
      borderWidth: 1,
      backgroundColor: isDark ? '#374151' : '#ffffff',
      borderColor: isDark ? '#4b5563' : '#d1d5db',
      color: isDark ? '#f9fafb' : '#111827',
    },
    inputFocused: {
      borderColor: '#3b82f6',
      borderWidth: 2,
    },
    inputDisabled: {
      backgroundColor: isDark ? '#1f2937' : '#f9fafb',
      color: isDark ? '#6b7280' : '#9ca3af',
    },
    searchIcon: {
      position: 'absolute',
      left: 12,
      zIndex: 1,
    },
    clearButton: {
      position: 'absolute',
      right: 12,
      padding: 4,
      borderRadius: 4,
      backgroundColor: isDark ? '#4b5563' : '#e5e7eb',
    },
    loadingContainer: {
      position: 'absolute',
      right: showClearButton ? 44 : 12,
      top: '50%',
      transform: [{ translateY: -10 }],
    },
    placeholderText: {
      color: isDark ? '#9ca3af' : '#6b7280',
    },
  });

  return (
    <View style={styles.container}>
      <View style={styles.inputWrapper}>
        <Ionicons
          name="search"
          size={20}
          color={isDark ? '#9ca3af' : '#6b7280'}
          style={styles.searchIcon}
        />
        
        <TextInput
          ref={inputRef}
          style={[
            styles.input,
            disabled && styles.inputDisabled,
          ]}
          value={inputValue}
          onChangeText={handleInputChange}
          onSubmitEditing={handleSubmit}
          onFocus={handleFocus}
          onBlur={handleBlur}
          placeholder={placeholder}
          placeholderTextColor={isDark ? '#9ca3af' : '#6b7280'}
          editable={!disabled}
          returnKeyType="search"
          autoCapitalize="none"
          autoCorrect={false}
          clearButtonMode="never" // We handle clear button manually
        />
        
        {showClearButton && inputValue.length > 0 && (
          <TouchableOpacity
            style={styles.clearButton}
            onPress={handleClear}
            disabled={disabled}
          >
            <Ionicons
              name="close"
              size={16}
              color={isDark ? '#9ca3af' : '#6b7280'}
            />
          </TouchableOpacity>
        )}
        
        {isSearching && (
          <View style={styles.loadingContainer}>
            <ActivityIndicator
              size="small"
              color={isDark ? '#3b82f6' : '#3b82f6'}
            />
          </View>
        )}
      </View>
    </View>
  );
};

export default SearchInput;
